version: '3'

services:
  frontend:
    build:
      context: .
    container_name: "frontend"
    ports:
      - "6565:6565"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always
    command: npm run start